services:
  web:
    container_name: analysis-app
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && daphne property_analysis.asgi:application -b 0.0.0.0 -p 8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    networks:
      default:
        aliases:
          - analysis-app
    depends_on:
      - redis
    
  redis:
    container_name: analysis-app-redis
    image: redis:latest
    networks:
      default:
        aliases:
          - analysis-app-redis

  celery:
    container_name: analysis-app-celery
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        echo 'Waiting for analysis-app and redis...';
        while ! nc -z analysis-app 8000 || ! nc -z redis 6379; do
          sleep 1;
        done;
        echo 'Web and Redis are up - starting celery worker';
        celery -A property_analysis worker --loglevel=info -Q analysis_queue
      "
    volumes:
      - .:/code
    depends_on:
      - redis
    
networks:
  default:
    name: shared_network
    external: True
