services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        daphne property_analysis.asgi:application -b 0.0.0.0 -p 8000
      "
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - redis
    container_name: analysis-app
    environment:
      - VIRTUAL_HOST=api-test.supersami.com
      - LETSENCRYPT_HOST=api-test.supersami.com
      - LETSENCRYPT_EMAIL=rolfgroenewold@gmail.com

  redis:
    image: redis:latest
    container_name: analysis-app-redis
  
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - DEFAULT_HOST=api-test.supersami.com

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/acme.sh:/etc/acme.sh
    environment:
      - NGINX_PROXY_CONTAINER=nginx_reverse_proxy
      - DEFAULT_EMAIL=rolfgroenewold@gmail.com

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        echo 'Waiting for analysis-app and redis...';
        while ! nc -z analysis-app 8000 || ! nc -z redis 6379; do
          sleep 1;
        done;
        echo 'Web and Redis are up - starting celery worker';
        celery -A property_analysis worker --loglevel=info
      "
    volumes:
      - .:/code
    depends_on:
      - redis
    container_name: analysis-app-celery
