# Generated by Django 4.2.15 on 2024-09-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='overall_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
